import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { environment } from '../../../../environments/environment';
import { ApiResponse } from '../../user-management/models/user-management.models';
import {
  CreateStrategicObjectiveRequest,
  StrategicObjective,
  StrategicObjectiveListResponse,
  UpdateStrategicObjectiveRequest,
} from '../models/strategic-objectives.models';

@Injectable({ providedIn: 'root' })
export class StrategicObjectiveService {
  private readonly http = inject(HttpClient);
  private readonly base = `${environment.apiUrl}/strategicobjectives`;

  /** Returns a paged list of strategic objectives, optionally filtered by org unit. */
  getAll(
    page: number,
    pageSize: number,
    orgUnitId?: string,
    includeDeleted = false,
  ): Observable<StrategicObjectiveListResponse> {
    let params = new HttpParams()
      .set('page', String(page))
      .set('pageSize', String(pageSize))
      .set('includeDeleted', String(includeDeleted));
    if (orgUnitId) params = params.set('orgUnitId', orgUnitId);
    return this.http
      .get<ApiResponse<StrategicObjectiveListResponse>>(this.base, { params })
      .pipe(map((res) => res.data));
  }

  /** Returns a single strategic objective by its ID. */
  getById(id: string): Observable<StrategicObjective> {
    return this.http
      .get<ApiResponse<StrategicObjective>>(`${this.base}/${id}`)
      .pipe(map((res) => res.data));
  }

  /** Returns all non-deleted strategic objectives for the specified org unit. */
  getByOrgUnit(orgUnitId: string): Observable<StrategicObjective[]> {
    return this.http
      .get<ApiResponse<StrategicObjective[]>>(`${this.base}/by-orgunit/${orgUnitId}`)
      .pipe(map((res) => res.data));
  }

  /** Creates a new strategic objective. ObjectiveCode is auto-generated by the server. */
  create(request: CreateStrategicObjectiveRequest): Observable<StrategicObjective> {
    return this.http
      .post<ApiResponse<StrategicObjective>>(this.base, request)
      .pipe(map((res) => res.data));
  }

  /** Updates the statement, description, and org unit of an existing objective. */
  update(id: string, request: UpdateStrategicObjectiveRequest): Observable<StrategicObjective> {
    return this.http
      .put<ApiResponse<StrategicObjective>>(`${this.base}/${id}`, request)
      .pipe(map((res) => res.data));
  }

  /** Soft-deletes a strategic objective. */
  softDelete(id: string): Observable<void> {
    return this.http.delete<void>(`${this.base}/${id}`);
  }

  /** Restores a previously soft-deleted strategic objective. */
  restore(id: string): Observable<StrategicObjective> {
    return this.http
      .post<ApiResponse<StrategicObjective>>(`${this.base}/${id}/restore`, null)
      .pipe(map((res) => res.data));
  }
}
